### ISSUE TITLE
Why "cc_ros_library" will generate .so and .a at the same time? And how can I choose one to pack?

### ISSUE THREAD

**Issue by sunzhec2702** [mvukov/rules_ros#12]
Hi Milan

This project is very nice and useful for ROS + bazel user.

But when I  try to use it and learn it, I didn't get why "cc_ros_library" will generate .so and .a at the same time? And how can I choose one to pack?

Would you please give me a help on this?

Thanks

**Comment by mvukov** [comment]
Hi, cc_ros_library is a macro that wraps Bazel's native [cc_library](https://bazel.build/reference/be/c-cpp#cc_library). When you build a library, then it creates .so and .a indeed; one typically doesn't build libs, but build executables and runs tests. But, when you build an executable then it doesn't build libraries, but links object files directly into an executable.

> And how can I choose one to pack?

Can you elaborate on this one, please?
