### ISSUE TITLE
Port to Bazel Modules

### ISSUE THREAD

**Issue by finn-ball** [mvukov/rules_ros#13]
Port the project to bazel modules as defined here:
https://bazel.build/external/module

As of Bazel 7, this is now the default way to bring in dependencies:
https://blog.bazel.build/2023/12/11/bazel-7-release.html

**Comment by finn-ball** [comment]
I have a rough draft working with your project, I can aim to create a PR in the next couple of days if this interests you.

**Comment by mvukov** [comment]
Hi, thanks for the initiative. Sure, please open a PR and we can iterate there.

**Comment by finn-ball** [comment]
I bring in boost differently to you. When I try your way, I get errors which I believe are to do with the includes:
https://github.com/nelhage/rules_boost/pull/553

**Comment by finn-ball** [comment]
This port is made a lot easier if we manage to port `rules_boost`:
https://github.com/nelhage/rules_boost/issues/546

**Comment by mvukov** [comment]
Done in #14 .
