### ISSUE TITLE
Deploy to BCR

### ISSUE THREAD

**Issue by hofbi** [mvukov/rules_ros#62]
With https://github.com/mvukov/rules_ros/pull/59 we already get all deps from BCR. How about contributing this module to BCR as well @mvukov?

With https://github.com/bazel-contrib/rules-template/tree/main/.bcr, this deployment could be even automated.

---

Linking https://github.com/bazelbuild/bazel-central-registry/issues/2223 as cross reference

**Comment by mvukov** [comment]
Sure, fine with me. Practical question: this repo follows live-at-head approach. Does BCR support this workflow?

**Comment by hofbi** [comment]
On BCR you can only download a dedicated pinned version. But if we setup the automated BCR deployment, we could do this for every commit on master or triggered by a tag.

If we don't want to do semver, we could also use yyyy-mm-dd-hh style versions.

**Comment by alexeagle** [comment]
Hi, I've had a few clients asking for ROS support so I could help out a bit in this repo.

I highly recommend doing releases. As one datapoint, it's required for repos in the Linux Foundation (https://bazel-contrib.github.io/SIG-rules-authors/hosting-policy.html#adding-criteria)
I suggest we set this up with a simple "push a tag to trigger a release" - so there's no effort required from maintainers. This is how it's done in the rules-template: https://github.com/bazel-contrib/rules-template/blob/main/CONTRIBUTING.md#releasing
